### ISSUE TITLE
Returns Functionality

### ISSUE THREAD

**Issue by raghvendras73** [drhenner/ror_ecommerce#156]
David,
            I see that returns functionality is there in the code for ROR-eCommerce. However I don't see it in the application. Is there a reason that this is disabled? How can I enable returns functionality for users and admins in the application?

Thanks for your help in advance.
Raghu

**Comment by drhenner** [comment]
Admin::Rma::ReturnAuthorizationsController

app/views/admin/history/orders/show.html.erb
78:    <% if @order.return_authorizations.size > 0 %>
79:       <%= link_to 'View RMAs', admin_rma_order_return_authorizations_path(@order),
83:      <%= link_to 'Create RMA', new_admin_rma_order_return_authorization_path(@order),

**Comment by raghvendras73** [comment]
Thanks a lot
