### ISSUE TITLE
Products filter 

### ISSUE THREAD

**Issue by jr1234** [drhenner/ror_ecommerce#157]
David,
We are trying to filter products based on check boxes. A criteria may have multiple check boxes and when each one of them is clicked, the data should further filter. This is similar to how Amazon does it too. We are preferring not to use the Submit button, as that makes the search less cleaner. 

When we submit the form_to by using submit button it works. It also works with the links. However when we use the jquery to submit the form, the response is coming as a HTML string and rails is unable to render it.

Please find the code we used below for the same. Any guidance to help this work will be well appreciated.

<%= form_tag('/fetch_products', format: "js", remote: true, id: "states") do |f|%>
<div class="col-md-3 s-d">
	<div class="w_sidebar">
		<section  class="sky-form">
			<h4>Shop By Region</h4>
			<div class="row1 scroll-pane">
				<div class="col col-4">
					<% states.each do |state| %>
					<label class="checkbox">
						<%= check_box_tag state.name, state.id, false, class:"checkbox" %><i></i>
						<%= state.name %>
						
					</label>
					<% end %>
				</div>
			</div>
		</section>
		<section  class="sky-form">
			<h4>shop by craft</h4>
			<div class="row1 scroll-pane">
				<div class="col col-4">
					<%= fields_for crafts do |cra| %>
					<% crafts.each do |craft| %>
					<label class="checkbox">
						<%= check_box_tag craft.name, craft.id, false, class:"checkbox" %><i></i>
						<%= craft.name %>
					</label>
					<% end %>
					<% end %>
				</div>
			</div>
		</section>
		<%= submit_tag("Search")%>
					<% end %>

2. $("#productsDiv").replaceWith("<%= escape_javascript(render(:partial => "index"))%>");

Thanks

**Comment by drhenner** [comment]
I'd probably do this in a different way.  I'd bind a jQuery ajax call to a button then submit with jQuery.  I don't have time to make the code for you right now but it shouldn't be too difficult.
