### ISSUE TITLE
Installing in AWS using Elastic Beanstalk.

### ISSUE THREAD

**Issue by jr1234** [drhenner/ror_ecommerce#158]
David,
When I am trying to deploy the app in AWS by using Elastic Beanstalk, it is giving me the error at FOG_DIRECTORY. If you have any Idea about this can you please help me on this. Here I am pasting the error log.

 :local_address => ""
    :local_port    => 40071
    :reason_phrase => "Moved Permanently"
    :remote_ip     => ""
    :status        => 301
    :status_line   => "HTTP/1.1 301 Moved Permanently\r\n"
  
  Excon::Errors::MovedPermanently: Expected(200) <=> Actual(301 Moved Permanently)
  excon.error.response
    :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>PermanentRedirect</Code><Message>**The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.**</Message><Bucket>elasticbeanstalk-ap-southeast-1-</Bucket><Endpoint>elasticbeanstalk-ap-southeast-1-.s3-ap-southeast-1.amazonaws.com</Endpoint><RequestId>B805F0BFB235E06E</RequestId><HostId>zAz+Je74Cr03o4BwwbR8dXajAEPXJW1eZRRAPzqqdaVuamdDR6NXo4TJ0fihDgeH8GTqwKZHRzo=</HostId></Error>"

Thanks

**Comment by drhenner** [comment]
Sorry I'm not exactly sure how to setup AWS.

**Comment by drhenner** [comment]
I'm closing this...  It is related to AWS more than this project.

If you found any information that could help others please post and I'll put it in the readme/wiki

Sorry I couldn't help
