### ISSUE TITLE
Change the position of image in Image group

### ISSUE THREAD

**Issue by raghvendras73** [drhenner/ror_ecommerce#159]
David,
            I am trying to check if it is possible for us to change the position of images in a image group without uploading the image again.

The 1st time we create the image group we would upload the images and set the image positions. At later point I would like to interchange the position of two images. Let us say I want to interchange position of image 1 and image 3. We have the option of making the selection there. However when we click create it does nothing unless we upload the images again. I was wondering if a work around is available where if just change the position of images and click Update(instead of Create). The position of images can change. 

This is essentially a feature where we may want to make one of our other images (other than 1) as the main image, which is required sometimes with eCommerce sites.

Thanks
Raghu

**Comment by drhenner** [comment]
The easiest thing to do is to directly change the position in the DB.  I think you could just edit the image but that might require an load of the image (

in `image_group.rb` you can change from:

       accepts_nested_attributes_for :images, :reject_if => proc { |t| (t['photo'].nil? && t['photo_from_link'].blank?) }, :allow_destroy => true

to: 

        accepts_nested_attributes_for :images, :reject_if => proc { |t| ((t['photo'].nil? && t['photo_from_link'].blank?) && t['id'].nil?) }, :allow_destroy => true

that should allow an edit without an image.  I will try to fix this on the weekend

**Comment by raghvendras73** [comment]
Thanks for your prompt response. We can't use the DB to update. Let me check this out for modifying image group and form level. We will let you know if we have any issues. Please keep us posted on the fix you are planning to deploy this weekend.

Thanks
Raghu

**Comment by raghvendras73** [comment]
This is completed. Thanks
