### ISSUE TITLE
Memcached End point setting

### ISSUE THREAD

**Issue by raghvendras73** [drhenner/ror_ecommerce#160]
David,
           Is there a place in the ROR where we specify the end point for the memcached? In AWS I have setup a Elasticache using memcache. I would need to know a place where we have to specify the memcached endpoint. When we are trying to use the application, the cache is not working and keeps giving error 127.0.0.1:11211 is not found. Your help is appreciated.

Thanks
Raghu

**Comment by drhenner** [comment]
I'd use this gem if I were to setup Elasticache using memcache.
https://github.com/ktheory/dalli-elasticache

For general setup locally I just follow these instructions:  `config/environments/development.rb`
https://github.com/mperham/dalli#usage-with-rails-3x-and-4x

**Comment by drhenner** [comment]
I'm closing this... It is related to AWS more than this project.

If you found any information that could help others please post and I'll put it in the readme/wiki

Sorry I couldn't help more
