### ISSUE TITLE
Can I sell digital products with ror_ecommerce?

### ISSUE THREAD

**Issue by amicheals** [drhenner/ror_ecommerce#161]
Can I sell digital products with ror_ecommerce?

**Comment by drhenner** [comment]
Sure,  You would just do a couple modifications for products / variants with digital downloads (I assume it is a download) 

1) create a download model
2) create associations:
   * variant has_many :downloads (maybe download a key or instructions or ???)
   * maybe product has_many :downloads (maybe download a key or instructions or ???)
3) when the purchase is complete allow the user to download the content.
4) set the inventory level to a billion items

That said I don't know the use case.  I have had this set up previously where the business needed the order_item to have the download.  Personally I'd have the MD5 of the order_item.id be the unique ID for the download.  

It does depend on what the product is though.  If you are selling "unique digital items" you might need to change the inventory class.  This could be done easily enough.  Just add a "DigitalInventory" class and each line item in the DigitalInventory table represents one item.  The DigitalInventory record could now contain any item-specific information.  In this case variants would `have_many :digital_inventories` and `order_item belongs_to :digital_inventory`  

If you are mixed between digital & physical product you should create a variant subclass (use SDI) and digital product would use digital_inventories & physical would use the normal inventory model
