### ISSUE TITLE
Would ror_ecommerce work fine under ruby-2.3.1 ?

### ISSUE THREAD

**Issue by acrolink** [drhenner/ror_ecommerce#168]

**Comment by drhenner** [comment]
I am upgrading the project today to ruby 2.3 & rails 5.  Once I'm done I'll push to github

**Comment by acrolink** [comment]
Thanks @drhenner .. Looking forward to running it

**Comment by drhenner** [comment]
Check out the rails5 branch.  I plan on merging it soon.  The tests pass but I will manually run it locally before I commit it to master

**Comment by drhenner** [comment]
All deprecations are resolved on the rails5 branch.  It should be ready to go.  I recommend using that branch if you are starting something new.

https://github.com/drhenner/ror_ecommerce/tree/rails5

https://github.com/drhenner/ror_ecommerce/pull/169
