### ISSUE TITLE
How to use payment gateway in development mode?

### ISSUE THREAD

**Issue by anasW** [drhenner/ror_ecommerce#175]
Hi

Which payment gateway did you use in ror_ecomm? Could you please help me in integrating payment gateway.

I am sorry I should not create this ticket as issue.

Thanks

**Comment by drhenner** [comment]
Changing this should do the trick 

https://github.com/drhenner/ror_ecommerce/blob/master/config/environments/production.rb#L125

**Comment by anasW** [comment]
Hi

Thank you for the response. But I am following this link http://drhenner.github.io/ror_ecommerce/config.html

I wanted to use Paypal and I have already created the credentials for the same but not able to see any transaction on the paypal. I have updated the credentials in config/settings.yml and config/env/dev, Do I need to change anything?

Thanks

**Comment by drhenner** [comment]
Uncomment this

    #::GATEWAY = ActiveMerchant::Billing::PaypalGateway.new(
    #  :login      => Settings.paypal.login,
    #  :password   => Settings.paypal.password,
    #  :signature  => Settings.paypal.signature
    #)

And remove this in the file I linked to (https://github.com/drhenner/ror_ecommerce/blob/master/config/environments/production.rb#L125):

    ::GATEWAY = ActiveMerchant::Billing::AuthorizeNetGateway.new(
      :login    => Settings.authnet.login,
      :password => Settings.authnet.password,
      :test     => true
    )

Note you should change 

config/environments/production.rb
config/environments/development.rb
config/environments/test.rb

**Comment by nrowegt** [comment]
In case anyone else has this issue, here's what worked for me:

~~~ruby
#development.rb
  # Send requests to the gateway's test servers
  ActiveMerchant::Billing::Base.mode = :test

  ::GATEWAY = ActiveMerchant::Billing::TrustCommerceGateway.new(
    :login    => 'TestMerchant',
    :password => 'password'
  )
~~~

**Comment by drhenner** [comment]
thanks @nrowegt
