### ISSUE TITLE
Paginate Products

### ISSUE THREAD

**Issue by lelelelemon** [drhenner/ror_ecommerce#179]
When I have 20k products to render, it will take more than 20seconds, so I think paginating the products will be a better design.

**Comment by drhenner** [comment]
👍

**Comment by drhenner** [comment]
I assume you are talking about the user facing products?  I will add pagination but I will say I intend users of ror_ecommerce to edit the user facing pages.  That was my thought around not adding it.

Thanks for the feedback!  I'll get on it ASAP

**Comment by drhenner** [comment]
done
