### ISSUE TITLE
Any other issues ?

### ISSUE THREAD

**Issue by lelelelemon** [drhenner/ror_ecommerce#181]
Hi, 
is this the only issue tracking system for ror_ecommerce, I want to get more issues to learn about the performance problems. If there is other link, please let me know.

Thanks a lot.

**Comment by drhenner** [comment]
This is the only issue tracker now.  People randomly contact me in odd channels but this is the best way to contact me.

If you looks at https://github.com/drhenner/stripe_commerce I did do a lot of speed optimizations in that repo.  (I added a good amount of caching)
